apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: elt-anp-bronze
  namespace: processing
spec:
  type: Python
  mode: cluster
  image: "lucasmullers/spark-k8s:v3.3.2"
  imagePullPolicy: Always
  mainApplicationFile: "s3a://spark-k8s-scripts/convert_tables_to_delta.py"
  sparkConf:
    "spark.hadoop.fs.s3.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "spark.hadoop.fs.s3a.path.style.access": "True"
    "spark.hadoop.fs.s3a.fast.upload": "True"
    "spark.hadoop.fs.s3a.multipart.size": "104857600"
    "fs.s3a.connection.maximum": "100"
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension"
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog"
  sparkVersion: "3.3.2"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    serviceAccount: spark-operator-spark
    envFrom:
      - secretRef:
          name: aws-secret
  executor:
    cores: 1
    instances: 8
    memory: "1024m"
    envFrom:
      - secretRef:
          name: aws-secret