apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: hello-world-spark-operator
  namespace: processing
spec:
  type: Scala
  mode: cluster
  image: "lucasmullers/spark-k8s:v3.3.2"
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.3.2.jar"
  sparkVersion: "3.3.2"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.2
    serviceAccount: spark-operator-spark
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.3.2