name: deploy_to_s3

on:
  push:
    branches: [main]
jobs:
  publish-dags:
    runs-on: ubuntu-latest
    env:
      DAGS_DIR: shell_data_integration
      DAGS_LOCAL_PATH: ./src/shell_data_integration/
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: Authenticate with credentials
        id: authenticate
        run: |
          echo -en "[default]\naws_access_key_id = ${{secrets.ACCESS_KEY}}\naws_secret_access_key = ${{secrets.SECRET_ACCESS_KEY}}" > ~/.aws/credentials
      - name: Check If dir exists
        id: check_file
        run:  |
          aws s3 ls s3://spark-k8s-scripts/