name: deploy_to_s3

on:
  push:
    branches: [main]
jobs:
  publish-dags:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'
    steps:
      - uses: actions/checkout@v3
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
      - name: Check If dir exists
        id: check_file
        run:  |
          aws s3 ls s3://spark-k8s-scripts/